export const SettingsActionTypes = {
    SET_THEME: 'SET_THEME',
    USE_SYSTEM_THEME: 'USE_SYSTEM_THEME',
    USE_HAPTICS: 'USE_HAPTICS',
    SET_UNITS: 'SET_UNITS',
    SET_APP_MODE: 'SET_APP_MODE',
    SET_DRIVE_SYSTEM: 'SET_DRIVE_SYSTEM'
}